### PR TITLE
Add city of Brest, France

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by souperneon** [comment]
Hi Frédéric!
Thank you for your request and apologies for not responding sooner.
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a [short usability study](http://goo.gl/forms/OIEdDWr7RIC04oqo2).
You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com).

Thanks,
Ekta.

**Comment by souperneon** [comment]
@frodrigo you can now create and download your custom extract for any place in the world here > https://mapzen.com/data/metro-extracts/
Give it a try and if you run into any issues, please write to us at [hello@mapzen.com](mailto:hello@mapzen.com). Closing this PR. 
Thanks,
Ekta.

**Comment by frodrigo** [comment]
Thank you, but since you switch I stopped using it. It's now more complicated to automate download on regular basis.

**Comment by migurski** [comment]
Sorry to hear it, Frédéric!

Just in case it helps, there is an "update" button on each custom extract which will re-submit the same request to get fresh data. Check out the bottom of pages like https://mapzen.com/data/metro-extracts/your-extracts/3cd8af7d22fa, look for “To update your extract with the latest OpenStreetMap data…”

**Pull request closed without merging**
