### PR TITLE
Add Bruges, Belgium

### PR DESCRIPTION
**Pull request by rfriberg**
Added one city: Bruges, Belgium

### CODE REVIEW

**Comment by KathleenLD** [comment]
Hi @rfriberg! Thanks for submitting this PR. Quick question-- did you intend for this extract to encompass multiple smaller cities around Bruges?

**Comment by rfriberg** [comment]
Hi @KathleenLD!  I don't necessarily need to include surrounding cities, but Bruges has such a long north-south footprint that it seems inevitable.

**Comment by KathleenLD** [comment]
@rfriberg ah, so you didn't mean to include Maldegem, Oudenberg, and Sterne? I can adjust it to be a little more closely cropped to Bruges, if you're alright with that.

**Comment by rfriberg** [comment]
@KathleenLD that's fine with me. Thank you.

**Comment by KathleenLD** [comment]
@rfriberg ok, I've added in a corrected Bruges; you'll be able to access the extract after this weekend. Thanks for your PR!

**Comment by rfriberg** [comment]
@KathleenLD thanks!

**Pull request merged**
