### PR TITLE
Update cities.json

### PR DESCRIPTION
**Pull request by BobHarper1**

### CODE REVIEW

**Comment by BobHarper1** [comment]
Got a 403 forbidden trying to connect to the flowdock api

**Comment by KathleenLD** [comment]
@heffergm would this have been caused by a flowdock issue, unrelated to the code?

**Comment by heffergm** [comment]
The tests fail for this pull because the json is invalid. See line 1152.

**Comment by KathleenLD** [comment]
Aha!

**Comment by KathleenLD** [comment]
Thansk @BobHarper1! I've tweaked this and merged it in, and you'll be able to see Derry in the Metro Extracts after this weekend.

**Comment by BobHarper1** [comment]
Thanks for the help @KathleenLD - I hadn't realised the issue was with my errant ,

**Pull request merged**
