### PR TITLE
Added Corpus Christi Texas

### PR DESCRIPTION
**Pull request by thrownblown**

### CODE REVIEW

**Comment by souperneon** [comment]
Hi Alex!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a [short usability study](http://goo.gl/forms/OIEdDWr7RIC04oqo2).
You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com).

Thanks,
Ekta.

**Comment by souperneon** [comment]
@thrownblown awesome! Thanks for trying it out :)
1. The URL will remain static to the custom extract you made. But it is a snapshot of the OSM data for the date and time you created it. Do you have a need to repeatedly download data for a specific region? It will great if we can chat and learn more about your process. It will help us make Metro Extracts more useful. If you are available next week, please let us know [here](http://goo.gl/forms/OIEdDWr7RIC04oqo2)
2. I hear you :) I love the feeling of contributing!

**Comment by thrownblown** [comment]
I download fresh extracts so that I have any recent changes in the underlying OSM planetfile. I don't do this often, typically once a month or less. I assume that people add and modify their cities fairly regularly. Looking through past downloands, there is some variance in file size. If I was more sophisticated with my script, I might compare their file sizes and only download ones that have changed. 

Thanks for listening to my feedback. All in all my issues are minor, and its generally much nicer to get the near instant download. I signed up for interview already!

**Comment by souperneon** [comment]
@thrownblown closing this and hoping you were able to get the extract you needed :)

**Pull request closed without merging**
